/** Les 40 avatars prédéfinis — fichiers dans public/avatars/, générés par scripts/make-avatars.py */
export const AVATARS = [
  { id: 'a01', label: 'Lion — Encre' },
  { id: 'a02', label: 'Lion — Grenat' },
  { id: 'a03', label: 'Lion — Bronze' },
  { id: 'a04', label: 'Lion — Or' },
  { id: 'a05', label: 'Lion — Marbre' },
  { id: 'a06', label: 'Aigle — Encre' },
  { id: 'a07', label: 'Aigle — Grenat' },
  { id: 'a08', label: 'Aigle — Bronze' },
  { id: 'a09', label: 'Aigle — Or' },
  { id: 'a10', label: 'Aigle — Marbre' },
  { id: 'a11', label: 'Colonne — Encre' },
  { id: 'a12', label: 'Colonne — Grenat' },
  { id: 'a13', label: 'Colonne — Bronze' },
  { id: 'a14', label: 'Colonne — Or' },
  { id: 'a15', label: 'Colonne — Marbre' },
  { id: 'a16', label: 'Bouclier — Encre' },
  { id: 'a17', label: 'Bouclier — Grenat' },
  { id: 'a18', label: 'Bouclier — Bronze' },
  { id: 'a19', label: 'Bouclier — Or' },
  { id: 'a20', label: 'Bouclier — Marbre' },
  { id: 'a21', label: 'Laurier — Encre' },
  { id: 'a22', label: 'Laurier — Grenat' },
  { id: 'a23', label: 'Laurier — Bronze' },
  { id: 'a24', label: 'Laurier — Or' },
  { id: 'a25', label: 'Laurier — Marbre' },
  { id: 'a26', label: 'Lyre — Encre' },
  { id: 'a27', label: 'Lyre — Grenat' },
  { id: 'a28', label: 'Lyre — Bronze' },
  { id: 'a29', label: 'Lyre — Or' },
  { id: 'a30', label: 'Lyre — Marbre' },
  { id: 'a31', label: 'Casque — Encre' },
  { id: 'a32', label: 'Casque — Grenat' },
  { id: 'a33', label: 'Casque — Bronze' },
  { id: 'a34', label: 'Casque — Or' },
  { id: 'a35', label: 'Casque — Marbre' },
  { id: 'a36', label: 'Soleil — Encre' },
  { id: 'a37', label: 'Soleil — Grenat' },
  { id: 'a38', label: 'Soleil — Bronze' },
  { id: 'a39', label: 'Soleil — Or' },
  { id: 'a40', label: 'Soleil — Marbre' },
]

export function avatarUrl(id) { return `/avatars/${id || 'a01'}.svg` }
